[project]
name = "elevans-kb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "myst-parser>=4.0.1",
    "readthedocs-sphinx-search>=0.3.2",
    "sphinx>=8.2.3",
    "sphinx-rtd-theme>=3.0.2",
]
